[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mi-libreria"
version = "0.1.0"
description = "Biblioteca personal para análisis de series de tiempo y música"
authors = [
    { name = "Edu" }
]
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "matplotlib",
    "numba"
]

[tool.setuptools.packages.find]
where = ["."]